name: samir_academy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
#  dio: ^5.8.0
#  injectable: ^2.3.2
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  firebase_core: ^2.28.0
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  fluttertoast: ^8.2.2
#  youtube_player_flutter: ^8.1.2
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
#  firebase_ui_auth: ^1.6.3
#  swipe_to: ^1.0.2
#  url_launcher: ^6.1.12
#  youtube_metadata: ^1.0.1
#  video_thumbnail: ^0.5.3
#  uuid: ^3.0.7
#  badges: ^3.1.2
#  audioplayers: ^5.1.0
#  flutter_link_previewer: ^3.2.2
#  flutter_chat_types: ^3.6.2
#  video_player: ^2.7.1
#  step_progress_indicator: ^1.0.2
#  youtube_player_flutter: ^8.1.2
  easy_localization: ^3.0.7
  image_picker: ^0.8.7
  youtube_player_flutter: ^8.1.2

#  flutter_inappwebview: ^5.7.2


dev_dependencies:
  build_runner: any
  injectable_generator: ^2.4.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/sounds/
    - assets/translations/
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800

