// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-4M2j0XB_BCa1rrckiTSlc_l9_Z2OuzA',
    appId: '1:617492442421:android:5db9322164b319e7b3f07c',
    messagingSenderId: '617492442421',
    projectId: 'samiracademy-524f0',
    storageBucket: 'samiracademy-524f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM5H7y_ddd61IfGRm7QiIlx1H0VRy5gwc',
    appId: '1:617492442421:ios:1761393832842634b3f07c',
    messagingSenderId: '617492442421',
    projectId: 'samiracademy-524f0',
    storageBucket: 'samiracademy-524f0.firebasestorage.app',
    androidClientId: '617492442421-ijc2dng3redb0p4mn2vratoojs6c7ei9.apps.googleusercontent.com',
    iosClientId: '617492442421-7kjfqv2bri3cjotbhhc0lbag2vt17uo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.samirAcademy',
  );
}
